version: "3.9"
services:
  server:
    image: registry.gitlab.com/altercode/astroneer-linux:latest
    volumes:
      - ./saves:/astroneer/Astro/Saved/SaveGames
      # Uncomment this if you want also the server configs to be mounted
      #- ./configs:/astroneer/Astro/Saved/Config/WindowsServer
    environment:
      OWNER_NAME: 'UberSprode'
      OWNER_GUID: '76561197969365714'
    ports:
      - "30877:30877/udp"
      - "30877:30877/tcp"
